// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (user_id, company_name, contact_name, contact_email, contact_phone, address, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, company_name, contact_name, contact_email, contact_phone, address, notes, archived_at, created_at, updated_at
`

type CreateClientParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	CompanyName  string      `json:"company_name"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Address      pgtype.Text `json:"address"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.UserID,
		arg.CompanyName,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Notes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, user_id, company_name, contact_name, contact_email, contact_phone, address, notes, archived_at, created_at, updated_at FROM clients
WHERE user_id = $1 and id = $2
`

type GetClientParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, arg.UserID, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Notes,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientByUserID = `-- name: ListClientByUserID :many
SELECT id, user_id, company_name, contact_name, contact_email, contact_phone, address, notes, archived_at, created_at, updated_at FROM clients
WHERE user_id = $1 and is_archived = false
ORDER BY created_at DESC
`

func (q *Queries) ListClientByUserID(ctx context.Context, userID uuid.UUID) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Notes,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
