// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetClient(ctx context.Context, arg GetClientParams) (Client, error)
	GetUnbillableTimeEntries(ctx context.Context, userID uuid.UUID) ([]GetUnbillableTimeEntriesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListClientByUserID(ctx context.Context, userID uuid.UUID) ([]Client, error)
	ListProjectsByClientID(ctx context.Context, arg ListProjectsByClientIDParams) ([]Project, error)
	ListProjectsByUserID(ctx context.Context, userID uuid.UUID) ([]Project, error)
	ListTasksByProjectID(ctx context.Context, arg ListTasksByProjectIDParams) ([]Task, error)
	ListTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error)
	ListTimeEntriesByRange(ctx context.Context, arg ListTimeEntriesByRangeParams) ([]ListTimeEntriesByRangeRow, error)
	StartTimer(ctx context.Context, arg StartTimerParams) (TimeEntry, error)
	StopTimer(ctx context.Context, id int32) (TimeEntry, error)
	StopTimerForUser(ctx context.Context, userID uuid.UUID) (TimeEntry, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
