// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, project_id, title, description, status, priority, due_date, estimated_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, user_id, title, description, status, priority, due_date, estimated_minutes, created_at, updated_at
`

type CreateTaskParams struct {
	UserID           uuid.UUID        `json:"user_id"`
	ProjectID        uuid.UUID        `json:"project_id"`
	Title            string           `json:"title"`
	Description      pgtype.Text      `json:"description"`
	Status           NullTaskStatus   `json:"status"`
	Priority         NullTaskPriority `json:"priority"`
	DueDate          pgtype.Date      `json:"due_date"`
	EstimatedMinutes pgtype.Int4      `json:"estimated_minutes"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.EstimatedMinutes,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByProjectID = `-- name: ListTasksByProjectID :many
SELECT id, project_id, user_id, title, description, status, priority, due_date, estimated_minutes, created_at, updated_at FROM tasks
WHERE user_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListTasksByProjectIDParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ListTasksByProjectID(ctx context.Context, arg ListTasksByProjectIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectID, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUserID = `-- name: ListTasksByUserID :many
SELECT id, project_id, user_id, title, description, status, priority, due_date, estimated_minutes, created_at, updated_at FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status NullTaskStatus `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
