// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, default_hourly_rate, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, full_name, default_hourly_rate, currency, created_at, updated_at
`

type CreateUserParams struct {
	Email             string      `json:"email"`
	PasswordHash      string      `json:"password_hash"`
	FullName          pgtype.Text `json:"full_name"`
	DefaultHourlyRate pgtype.Int4 `json:"default_hourly_rate"`
	Currency          pgtype.Text `json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.DefaultHourlyRate,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.DefaultHourlyRate,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, default_hourly_rate, currency, created_at, updated_at FROM users WHERE email = $1 LIMIT $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, limit int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, limit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.DefaultHourlyRate,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, default_hourly_rate, currency, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.DefaultHourlyRate,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
